imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less:
                    node:       /usr/local/bin/node
                    node_paths: [/usr/local/lib/node_modules]
                    apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
       bootstrap_css:
                  assets_dir:  %kernel.root_dir%/../vendor/twitter/bootstrap
                  jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Ges\UserBundle\Entity\User
    registration:
        form:
            type: fos_user_registration

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: GesEnquiryBundle:Pagination:sliding.html.twig     # sliding pagination controls template

services:
    fos_user.registration.form.type:
        class: Ges\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, %security.role_hierarchy.roles%]
        tags:
            - { name: form.type, alias: fos_user_registration}
    fos_user.register:
        class: Ges\UserBundle\EventListener\RegisterListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    fos_user.listener.authentication:
#        class: Ges\UserBundle\EventListener\AuthenticationListener
        class: Ges\UserBundle\EventListener\RegisterListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }