_welcome:
    pattern:  /
    defaults: { _controller: GesEnquiryBundle:Default:index }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

department:
    resource: "@GesEnquiryBundle/Controller/"
    type:    annotation
    prefix:   /

enquirylevel:
    resource: "@GesEnquiryBundle/Controller/"
    type:    annotation
    prefix:   /

enquirytype:
     resource: "@GesEnquiryBundle/Controller/"
     type:    annotation
     prefix:   /

enquiry:
     resource: "@GesEnquiryBundle/Controller/"
     type:    annotation
     prefix:   /
