<?php

namespace Ges\EnquiryBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EnquiryLevelController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ges\EnquiryBundle\Controller\EnquiryLevelController();
        return $instance;
    }
}
